version: '3'

services:
  dao_web3:
    container_name: dao-web3-services
    build: ./dao-web3/
    ports:
      - 5050:5050
    volumes:
      - ./data:/var/run/data
    working_dir: /var/run/dao
    depends_on:
      - redis
    links:
      - redis
   
    

  redis:
    image: redis:latest
    expose:
      - "6379"